deprecated:
- name: 天津大学科学技术发展研究院
  fakeid: MzIzMjEyMTEyNw==
  last_update: 2017-10-24 16:03
  removed_date: '2026-08-30'
- name: 天津大学科学技术与社会研究中心
  fakeid: MzU2MDEwMzQ2MA==
  last_update: 2023-06-16 10:12
  removed_date: '2026-08-30'
- name: 天津大学综合服务大厅
  fakeid: MzI3MjIwNTMyNA==
  last_update: 2024-08-30 17:59
  removed_date: '2026-08-30'
- name: 天大历史同好会
  fakeid: MzI3Mjg3NzM0MQ==
  last_update: 2022-10-03 21:52
  removed_date: '2026-08-30'
- name: 国创计划
  fakeid: Mzg5NzQ0MTI5MA==
  last_update: 2022-07-14 08:18
  removed_date: '2026-08-30'
- name: 天津大学前沿技术研究院
  fakeid: MzAwODQ4ODgxMQ==
  last_update: 2023-09-28 08:36
  removed_date: '2026-08-30'
- name: 天津大学小幼医工作部
  fakeid: MzIwNDcyMDM0OA==
  last_update: 2023-11-19 18:21
  removed_date: '2026-08-30'
- name: 天津大学高端教育培训
  fakeid: MzA5MjcwNTcwNw==
  last_update: 2022-03-10 16:16
  removed_date: '2026-08-30'
- name: 天大化工书院管委会
  fakeid: MzA4NTYzMDk0Mw==
  last_update: 2019-09-08 22:36
  removed_date: '2026-08-30'
- name: 天大交通
  fakeid: MzU0MzgwMzc1Mg==
  last_update: 2024-05-23 11:45
  removed_date: '2026-08-30'
- name: 天大学生会
  fakeid: MjM5NjM3ODMyNA==
  last_update: 2023-05-17 20:11
  removed_date: '2026-08-30'
- name: 天津大学发展规划处
  fakeid: MzIwNzEwNzEwMA==
  last_update: 2020-05-12 16:50
  removed_date: '2026-08-30'
